
USE BankStage;
CREATE TABLE BankAccount (
	BankAccountId BIGINT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	BankId VARCHAR(10) NOT NULL,
	AccountNo VARCHAR(12) NOT NULL UNIQUE,
	Balance DECIMAL(16,2) NOT NULL,
	Status VARCHAR(10) NOT NULL,
	StatusDate DATETIME2 NOT NULL,
	CreatedBy VARCHAR(50) NOT NULL,
	CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
	ModifiedBy VARCHAR(50) NOT NULL,
	ModifiedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)

INSERT INTO BankAccount 
VALUES ('SE00000001', '109200000003', '0.35', 'CLOSED', SYSUTCDATETIME(), 'SYSTEM', SYSUTCDATETIME(), 'SYSTEM', SYSUTCDATETIME());